// FILE: docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: attendance_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: attendance_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: attendance_db
      DB_SSLMODE: disable
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped

volumes:
  postgres_data:
